"""initial schema

Revision ID: 0eefcbe8c901
Revises: 
Create Date: 2026-10-03 05:23:41.963128

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0eefcbe8c901"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration.

    Extensions are created before any table: ``vector`` backs
    ``chunks.embedding``/``ix_chunks_embedding`` and ``pg_trgm`` backs the fuzzy
    search indexes on ``projects.name`` and ``chunks.content``.

    ``uuid-ossp`` is created best-effort — the application generates UUIDs in
    Python (``uuid.uuid4``), so the extension is pure convenience and is not
    available on every managed PostgreSQL service. Its absence must never abort
    a deployment.
    """
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute(
        """
        DO $$
        BEGIN
            CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
        EXCEPTION WHEN OTHERS THEN
            RAISE NOTICE 'uuid-ossp unavailable (%): continuing without it', SQLERRM;
        END
        $$;
        """
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=True),
        sa.Column("supabase_uid", sa.String(length=64), nullable=False),
        sa.Column("plan_tier", sa.String(length=32), server_default="free", nullable=False),
        sa.Column("monthly_credits_used", sa.Integer(), server_default="0", nullable=False),
        sa.Column("monthly_credits_limit", sa.Integer(), server_default="10", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "plan_tier IN ('free', 'pro', 'agency', 'enterprise')",
            name=op.f("ck_users_plan_tier_valid"),
        ),
        sa.CheckConstraint(
            "monthly_credits_limit >= 0", name=op.f("ck_users_credits_limit_non_negative")
        ),
        sa.CheckConstraint(
            "monthly_credits_used >= 0", name=op.f("ck_users_credits_used_non_negative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_supabase_uid"), "users", ["supabase_uid"], unique=True)
    op.create_table(
        "projects",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("domain_url", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_projects_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    op.create_index(
        "ix_projects_name_trgm",
        "projects",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_index("ix_projects_user_active", "projects", ["user_id", "is_active"], unique=False)
    op.create_index(op.f("ix_projects_user_id"), "projects", ["user_id"], unique=False)
    op.create_table(
        "domains",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("sitemap_url", sa.String(length=2048), nullable=True),
        sa.Column("robots_txt", sa.Text(), nullable=True),
        sa.Column("last_crawled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("crawl_status", sa.String(length=32), server_default="pending", nullable=False),
        sa.Column("has_json_ld", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("has_sitemap", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "heading_structure_valid", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "meta_description_present",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("canonical_set", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "robots_txt_allows_crawl", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "crawl_status IN ('pending', 'crawling', 'completed', 'failed')",
            name=op.f("ck_domains_crawl_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_domains_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_domains")),
        sa.UniqueConstraint("project_id", "url", name="project_url"),
    )
    op.create_index(op.f("ix_domains_project_id"), "domains", ["project_id"], unique=False)
    op.create_index(
        "ix_domains_project_status", "domains", ["project_id", "crawl_status"], unique=False
    )
    op.create_index(op.f("ix_domains_url"), "domains", ["url"], unique=False)
    op.create_table(
        "tracked_prompts",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("query_text", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=32), server_default="informational", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('informational', 'consideration', 'transactional', 'navigational')",
            name=op.f("ck_tracked_prompts_category_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_tracked_prompts_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tracked_prompts")),
        sa.UniqueConstraint("project_id", "query_text", name="project_query"),
    )
    op.create_index(
        "ix_tracked_prompts_project_active",
        "tracked_prompts",
        ["project_id", "is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tracked_prompts_project_id"), "tracked_prompts", ["project_id"], unique=False
    )
    op.create_table(
        "audits",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("domain_id", sa.UUID(), nullable=False),
        sa.Column("target_url", sa.String(length=2048), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="queued", nullable=False),
        sa.Column("technical_readiness_score", sa.Float(), nullable=True),
        sa.Column("semantic_alignment_score", sa.Float(), nullable=True),
        sa.Column("evidentiary_density_score", sa.Float(), nullable=True),
        sa.Column("machine_readability_score", sa.Float(), nullable=True),
        sa.Column("pcs_score", sa.Float(), nullable=True),
        sa.Column("raw_html", sa.Text(), nullable=True),
        sa.Column("clean_markdown", sa.Text(), nullable=True),
        sa.Column("word_count", sa.Integer(), nullable=True),
        sa.Column("json_ld_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("score_breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'crawling', 'analyzing', 'completed', 'failed')",
            name=op.f("ck_audits_status_valid"),
        ),
        sa.CheckConstraint(
            "pcs_score IS NULL OR (pcs_score >= 0 AND pcs_score <= 1)",
            name=op.f("ck_audits_pcs_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["domain_id"],
            ["domains.id"],
            name=op.f("fk_audits_domain_id_domains"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_audits_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audits")),
    )
    op.create_index(op.f("ix_audits_domain_id"), "audits", ["domain_id"], unique=False)
    op.create_index(
        "ix_audits_project_created", "audits", ["project_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_audits_project_id"), "audits", ["project_id"], unique=False)
    op.create_index("ix_audits_project_status", "audits", ["project_id", "status"], unique=False)
    op.create_index("ix_audits_target_url", "audits", ["target_url"], unique=False)
    op.create_table(
        "chunks",
        sa.Column("audit_id", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("char_count", sa.Integer(), nullable=True),
        sa.Column("xpath_location", sa.String(length=1024), nullable=True),
        sa.Column("heading_path", sa.String(length=512), nullable=True),
        sa.Column("embedding", Vector(1536), nullable=True),
        sa.Column("is_embedded", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('english', content)", persisted=True),
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["audit_id"], ["audits.id"], name=op.f("fk_chunks_audit_id_audits"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chunks")),
        sa.UniqueConstraint("audit_id", "chunk_index", name="audit_chunk_index"),
    )
    op.create_index(op.f("ix_chunks_audit_id"), "chunks", ["audit_id"], unique=False)
    op.create_index("ix_chunks_audit_index", "chunks", ["audit_id", "chunk_index"], unique=False)
    op.create_index(
        "ix_chunks_content_trgm",
        "chunks",
        ["content"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"content": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_chunks_embedding",
        "chunks",
        ["embedding"],
        unique=False,
        postgresql_using="ivfflat",
        postgresql_with={"lists": 100},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        "ix_chunks_search", "chunks", ["search_vector"], unique=False, postgresql_using="gin"
    )
    op.create_table(
        "crawl_jobs",
        sa.Column("audit_id", sa.UUID(), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("method", sa.String(length=32), server_default="scrapy", nullable=False),
        sa.Column("status", sa.String(length=32), server_default="pending", nullable=False),
        sa.Column("http_status_code", sa.Integer(), nullable=True),
        sa.Column("content_type", sa.String(length=255), nullable=True),
        sa.Column("response_time_ms", sa.Integer(), nullable=True),
        sa.Column("response_size_bytes", sa.Integer(), nullable=True),
        sa.Column("is_spa_detected", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "playwright_fallback_used",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "robots_txt_allowed", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "method IN ('scrapy', 'playwright', 'httpx')", name=op.f("ck_crawl_jobs_method_valid")
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'completed', 'failed', 'cancelled')",
            name=op.f("ck_crawl_jobs_status_valid"),
        ),
        sa.CheckConstraint("retry_count >= 0", name=op.f("ck_crawl_jobs_retry_count_non_negative")),
        sa.ForeignKeyConstraint(
            ["audit_id"],
            ["audits.id"],
            name=op.f("fk_crawl_jobs_audit_id_audits"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crawl_jobs")),
    )
    op.create_index(op.f("ix_crawl_jobs_audit_id"), "crawl_jobs", ["audit_id"], unique=False)
    op.create_index(
        "ix_crawl_jobs_audit_status", "crawl_jobs", ["audit_id", "status"], unique=False
    )
    op.create_index(
        "ix_crawl_jobs_status_created", "crawl_jobs", ["status", "created_at"], unique=False
    )
    op.create_table(
        "simulation_runs",
        sa.Column("audit_id", sa.UUID(), nullable=False),
        sa.Column("prompt_id", sa.UUID(), nullable=False),
        sa.Column("engine", sa.String(length=32), server_default="chatgpt", nullable=False),
        sa.Column("model_name", sa.String(length=120), nullable=True),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.Column("run_index", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="pending", nullable=False),
        sa.Column("generated_response", sa.Text(), nullable=True),
        sa.Column("cited_urls", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "target_url_cited", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("nli_entailment_score", sa.Float(), nullable=True),
        sa.Column("nli_label", sa.String(length=32), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "nli_label IS NULL OR nli_label IN ('entailment', 'contradiction', 'neutral')",
            name=op.f("ck_simulation_runs_nli_label_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'completed', 'failed')",
            name=op.f("ck_simulation_runs_status_valid"),
        ),
        sa.CheckConstraint("run_index >= 1", name=op.f("ck_simulation_runs_run_index_positive")),
        sa.CheckConstraint(
            "temperature >= 0 AND temperature <= 2",
            name=op.f("ck_simulation_runs_temperature_range"),
        ),
        sa.ForeignKeyConstraint(
            ["audit_id"],
            ["audits.id"],
            name=op.f("fk_simulation_runs_audit_id_audits"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["prompt_id"],
            ["tracked_prompts.id"],
            name=op.f("fk_simulation_runs_prompt_id_tracked_prompts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_simulation_runs")),
        sa.UniqueConstraint(
            "audit_id", "prompt_id", "temperature", "run_index", name="audit_prompt_temp_run"
        ),
    )
    op.create_index(
        op.f("ix_simulation_runs_audit_id"), "simulation_runs", ["audit_id"], unique=False
    )
    op.create_index(
        "ix_simulation_runs_audit_prompt",
        "simulation_runs",
        ["audit_id", "prompt_id"],
        unique=False,
    )
    op.create_index(
        "ix_simulation_runs_cited", "simulation_runs", ["target_url_cited"], unique=False
    )
    op.create_index(
        op.f("ix_simulation_runs_prompt_id"), "simulation_runs", ["prompt_id"], unique=False
    )
    op.create_table(
        "citation_logs",
        sa.Column("simulation_run_id", sa.UUID(), nullable=False),
        sa.Column("cited_url", sa.String(length=2048), nullable=False),
        sa.Column("citation_position", sa.Integer(), nullable=False),
        sa.Column("sentence_text", sa.Text(), nullable=True),
        sa.Column("word_count", sa.Integer(), nullable=True),
        sa.Column("is_target_url", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("position_weight", sa.Float(), nullable=True),
        sa.Column("imp_pwc", sa.Float(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "citation_position >= 1", name=op.f("ck_citation_logs_citation_position_positive")
        ),
        sa.CheckConstraint(
            "position_weight IS NULL OR (position_weight >= 0 AND position_weight <= 1)",
            name=op.f("ck_citation_logs_position_weight_range"),
        ),
        sa.CheckConstraint(
            "word_count IS NULL OR word_count >= 0",
            name=op.f("ck_citation_logs_word_count_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["simulation_run_id"],
            ["simulation_runs.id"],
            name=op.f("fk_citation_logs_simulation_run_id_simulation_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_citation_logs")),
        sa.UniqueConstraint("simulation_run_id", "citation_position", name="run_position"),
    )
    op.create_index("ix_citation_logs_cited_url", "citation_logs", ["cited_url"], unique=False)
    op.create_index(
        "ix_citation_logs_run",
        "citation_logs",
        ["simulation_run_id", "citation_position"],
        unique=False,
    )
    op.create_index(
        op.f("ix_citation_logs_simulation_run_id"),
        "citation_logs",
        ["simulation_run_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_citation_logs_simulation_run_id"), table_name="citation_logs")
    op.drop_index("ix_citation_logs_run", table_name="citation_logs")
    op.drop_index("ix_citation_logs_cited_url", table_name="citation_logs")
    op.drop_table("citation_logs")
    op.drop_index(op.f("ix_simulation_runs_prompt_id"), table_name="simulation_runs")
    op.drop_index("ix_simulation_runs_cited", table_name="simulation_runs")
    op.drop_index("ix_simulation_runs_audit_prompt", table_name="simulation_runs")
    op.drop_index(op.f("ix_simulation_runs_audit_id"), table_name="simulation_runs")
    op.drop_table("simulation_runs")
    op.drop_index("ix_crawl_jobs_status_created", table_name="crawl_jobs")
    op.drop_index("ix_crawl_jobs_audit_status", table_name="crawl_jobs")
    op.drop_index(op.f("ix_crawl_jobs_audit_id"), table_name="crawl_jobs")
    op.drop_table("crawl_jobs")
    op.drop_index("ix_chunks_search", table_name="chunks", postgresql_using="gin")
    op.drop_index(
        "ix_chunks_embedding",
        table_name="chunks",
        postgresql_using="ivfflat",
        postgresql_with={"lists": 100},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_index(
        "ix_chunks_content_trgm",
        table_name="chunks",
        postgresql_using="gin",
        postgresql_ops={"content": "gin_trgm_ops"},
    )
    op.drop_index("ix_chunks_audit_index", table_name="chunks")
    op.drop_index(op.f("ix_chunks_audit_id"), table_name="chunks")
    op.drop_table("chunks")
    op.drop_index("ix_audits_target_url", table_name="audits")
    op.drop_index("ix_audits_project_status", table_name="audits")
    op.drop_index(op.f("ix_audits_project_id"), table_name="audits")
    op.drop_index("ix_audits_project_created", table_name="audits")
    op.drop_index(op.f("ix_audits_domain_id"), table_name="audits")
    op.drop_table("audits")
    op.drop_index(op.f("ix_tracked_prompts_project_id"), table_name="tracked_prompts")
    op.drop_index("ix_tracked_prompts_project_active", table_name="tracked_prompts")
    op.drop_table("tracked_prompts")
    op.drop_index(op.f("ix_domains_url"), table_name="domains")
    op.drop_index("ix_domains_project_status", table_name="domains")
    op.drop_index(op.f("ix_domains_project_id"), table_name="domains")
    op.drop_table("domains")
    op.drop_index(op.f("ix_projects_user_id"), table_name="projects")
    op.drop_index("ix_projects_user_active", table_name="projects")
    op.drop_index(
        "ix_projects_name_trgm",
        table_name="projects",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_table("projects")
    op.drop_index(op.f("ix_users_supabase_uid"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
